version: "2"
linters:
  disable:
    - exhaustive
    - errcheck
    - unused
  settings:
    exhaustive:
      check:
        - "switch"
        - "map"
    staticcheck:
      checks:
        - "-QF1001" # disable "could apply De Morgan's law"
