name: IaC Scanning
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    paths:
      - '**.tf'
      - '**.yaml'
      - '**.json'
      - 'Dockerfile'
      - 'docker-compose*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  checkov:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8b5
      - name: Install checkov
        run: pip install checkov
      - name: Run checkov
        run: checkov -d . -o sarif --framework dockerfile,github_actions || true
        continue-on-error: true
